---
acme_staging: https://acme-staging-v02.api.letsencrypt.org/directory
acme_production: https://acme-v02.api.letsencrypt.org/directory
certmanager_acme_challenge: http    # dns, tls, or http
certmanager_acme_dns_provider: cloudflare
certmanager_acme_dns_secret_name: cloudflare-token-secret
certmanager_acme_dns_token_key: 123abc
certmanager_acme_dns_token_name: cloudflare-token
certmanager_acme_dns_token_user: "{{ certmanager_acme_email }}"
certmanager_acme_email: user@example.com
certmanager_acme_http_ingressclass: traefik-external
certmanager_acme_server: "{{ acme_staging }}"
certmanager_crd_file: cert-manager.crds.yaml
certmanager_crd_url: "{{ certmanager_crd_url_base }}/{{ certmanager_crd_url_version }}"
certmanager_crd_url_base: "https://github.com/cert-manager/cert-manager/releases/download/"
certmanager_crd_url_version: "v{{ chart_version }}/{{ certmanager_crd_file }}"
certmanager_deploy_annotations: []
certmanager_deploy_labels: []
certmanager_dns_recursive:
  - 1.1.1.1
  - 9.9.9.9
certmanager_dns_recursive_only: true
certmanager_issuer_acme: false
certmanager_issuer_acme_key_name: acme-issuer-account-key
certmanager_issuer_acme_name: letsencrypt
certmanager_issuer_selfsign: true
certmanager_issuer_selfsign_name: selfsigned
certmanager_log_level: 2    # Range of 0 - 6 with 6 being the most verbose.
certmanager_name: "{{ k8s_namespace }}"
certmanager_pod_annotations: []
certmanager_pod_dns_policy: None
certmanager_pod_dns_servers: "{{ certmanager_dns_recursive }}"
certmanager_pod_labels: []
certmanager_service_annotations: []
certmanager_service_labels: []
certmanager_replicas: 1
chart_ref: jetstack/cert-manager
chart_repository_name: jetstack
chart_version: "1.13.2"
helm_repo_pass: "{{ undef() }}"
helm_repo_url: https://charts.jetstack.io
helm_repo_user: "{{ undef() }}"
k8s_config: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_KUBECONFIG', default=undef()) }}"
k8s_context: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_CONTEXT', default=undef()) }}"
k8s_namespace: cert-manager
